#!/usr/bin/env python3
"""End-to-end demo: a teacher's SOP -> read offline (docintel) -> resolve context -> adapt output.

Reads a school SOP file with the OFFLINE document engine, resolves a teaching-context contract from
the district + school type + that SOP, derives the context-driven adaptations, and writes a worked
example artifact (with the context envelope in its metadata). Run:

    python3 tools/context_demo.py            # uses examples/context/sample-school-sop.md
    python3 tools/context_demo.py <sop_path> [--out <md>]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "shared"))

import context as ctxlib  # shared/context/context.py
import docintel           # shared/docintel


def read_sop(path: Path):
    import re
    doc = docintel.Pipeline().run(path.read_bytes(), str(path))
    directives = re.findall(r"(?m)^\s*\d+\.\s+\S", path.read_text(encoding="utf-8", errors="ignore"))
    return {
        "retrieval_state": doc.diagnostics.get("retrieval_state"),
        "blocks": doc.properties.get("block_count", 0),
        "directives": directives,
    }


def adaptations(context):
    rules = ctxlib.school_type_rules(context["school_type"])
    return {
        "standards_applicability": context["standards_applicability"],
        "school_type_overrides": rules.get("overrides_baseline", []),
        "sop_override_targets": rules.get("sop_overrides", []),
        "instructional_model": context["instructional_model"],
        "calendar": context["calendar"],
    }


def main(argv) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("sop", nargs="?", default=str(ROOT / "examples/context/sample-school-sop.md"))
    ap.add_argument("--out", default=str(ROOT / "examples/context/example-context-adapted-lesson.md"))
    a = ap.parse_args(argv)

    sop_path = Path(a.sop)
    sop = read_sop(sop_path)
    rel = sop_path.relative_to(ROOT) if sop_path.is_relative_to(ROOT) else sop_path

    context = ctxlib.build_context(
        school_type="charter_public", district="Orange", school_name="Beacon Charter Academy",
        subject="Mathematics", grade_band="6-8", instructional_model="blended", calendar="block",
        program=["general"],
        sop_refs=[{"id": "sop-beacon-instructional", "scope": "school", "path": str(rel),
                   "label": "Beacon Charter Academy Instructional SOP"}])
    ctxlib.apply_override(context, "Grade on the school's standards-based 1-4 scale per SOP",
                          by="teacher", effect="grading scale = SBG 1-4")
    valid = ctxlib.validate_context(context)
    adapt = adaptations(context)

    md = f"""# Worked example — SOP-adapted lesson (end to end)

> Generated by `tools/context_demo.py`. Shows the loop: **upload an SOP → read it offline → resolve
> the teaching context → produce an artifact adapted to that context.** Sample/placeholder data only;
> `human_review_required: true`.

## 1. SOP read **offline** (docintel)
- Source: `{rel}`
- Retrieval state: **{sop['retrieval_state']}** · blocks: {sop['blocks']} · directives detected: {len(sop['directives'])}
- No network used to read the document.

## 2. Resolved context contract
```json
{json.dumps(context, indent=2)}
```
Validation: {json.dumps(valid)}

## 3. Context-driven adaptations
- Standards applicability: **{adapt['standards_applicability']}** (charter → B.E.S.T./NGSSS apply).
- School-type overrides honored: {', '.join(adapt['school_type_overrides'])}.
- SOP override targets: {', '.join(adapt['sop_override_targets'])}.
- Instructional model **{adapt['instructional_model']}** + **{adapt['calendar']}** schedule → 90-min
  block pacing, blended in-class + LMS.

## 4. Adapted artifact (excerpt)
A lesson built for THIS context differs from the traditional-public default:
- **Block pacing:** one standard cluster per 90-minute block (not a 50-min period).
- **Standards-based grading 1-4** (per SOP override), not points/percentages.
- **Weekly common formative assessment** aligned to the week's B.E.S.T. benchmark (per SOP).
- **UDL** option for representation, action/expression, and engagement (per SOP).
- **Family-contact rule:** within 24h of a grade of 1 (routes to `family-communication`).
- **Governance:** contract-affecting changes route to the charter board (`school-administration`).

## Metadata (per `protocols/metadata-schema.md`)
```yaml
artifact_type: lesson-plan
subject: Mathematics
grade_band: 6-8
standards_set: FL-BEST-Math
context: {{ district: Orange, school_type: charter_public, instructional_model: blended,
           calendar: block, sop_refs: [Beacon Charter Academy Instructional SOP] }}
human_review_required: true
```
"""
    Path(a.out).write_text(md, encoding="utf-8")
    print(f"SOP read offline: retrieval_state={sop['retrieval_state']}, blocks={sop['blocks']}")
    print(f"context valid: {valid['valid']} | school_type={context['school_type']} "
          f"district={context['district']['name']} overrides={len(context['overrides'])}")
    print(f"wrote worked example -> {Path(a.out).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
